dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}

dependencies:
  # - <organizzation/repo>@<version> scaricate da GitHub
  - smartcontractkit/chainlink-brownie-contracts@0.2.1
  - smartcontractkit/chainlink@1.2.1
  - OpenZeppelin/openzeppelin-contracts@4.5.0
compiler:
  # spiegare al compiler che @chainlink punta alla dipendenza su GitHub
  solc:
    remappings:
      - '@chainlink-brownie=smartcontractkit/chainlink-brownie-contracts@0.2.1'
      - '@chainlink=smartcontractkit/chainlink@1.2.1'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0'

networks:
  default: development
  mainnet-fork:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
  rinkeby:
    eth_usd_price_feed: "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"
    verify: True